name: Build and deploy to Kuroco front
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. 疑似ビルド（package.jsonに書いたbuildコマンドを実行）
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Build static site
        run: |
          npm install
          npm run build

      # 2. KurocoFrontへのアップロード実行
      - name: Deploy
        uses: Kuroco-front/kuroco-front-action@v1
        with:
          token: ${{ secrets.KUROCO_FRONT_TOKEN }}
          repository_id: 24021400564
          output_dir: out
          
